version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - dependencies
    schedule:
      interval: 'weekly'
