modLoader = "javafml"
loaderVersion = "[35,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/TMUniversal/RBM/issues"
displayURL = "https://github.com/TMUniversal/RBM"
#updateJSONURL=""
logoFile = "logo.png"
credits = "Thanks to RX_13 for ideas and art."
authors = "TMUniversal"

[[mods]]
modId = "rbm"
version = "${file.jarVersion}"
displayName = "Random Bulls**t Mod"
description = '''
Adds a bunch of random stuff we think is fun/useful/neat.

We were bored...
'''

[[dependencies.rbm]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rbm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rbm]]
modId = "placebo"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rbm]]
modId = "jei"
mandatory = false
versionRange = "[7.6.0,)"
ordering = "NONE"
side = "BOTH"
